channels:
  - conda-forge
  - bioconda
dependencies:
  - conda-forge::r-base
  - conda-forge::r-scales=1.4.0
  - conda-forge::r-readr=2.1.5
  - conda-forge::r-gtools=3.9.5
  - bioconda::bioconductor-biomart