channels:
  - conda-forge
  - bioconda
dependencies:
  - conda-forge::r-base
  - conda-forge::r-scales=1.4.0
  - conda-forge::r-gtools=3.9.5
  - bioconda::bioconductor-methylKit=1.35.0
  - bioconda::bioconductor-genomation=1.38.0